export default [
  {
    name: "Mercurio",
    radius: 0.5,
    distance: 10,
    color: 0xaaaaaa,
    texture: "textures/planets/mercury/main_texture.jpg",
    orbitSpeed: 0.02,
  },
  {
    name: "Venus",
    radius: 0.9,
    distance: 15,
    color: 0xffcc00,
    texture: "textures/planets/venus/main_texture.jpg",
    orbitSpeed: 0.015,
  },
  {
    name: "Marte",
    radius: 0.7,
    distance: 25,
    color: 0xff0000,
    texture: "textures/planets/mars/main_texture.jpg",
    orbitSpeed: 0.008,
  },
  {
    name: "Júpiter",
    radius: 2.5,
    distance: 35,
    color: 0xffa500,
    texture: "textures/planets/jupiter/main_texture.jpg",
    orbitSpeed: 0.006,
  },
  {
    name: "Saturno",
    radius: 2,
    distance: 45,
    color: 0xffd700,
    texture: "textures/planets/saturn/main_texture.jpg",
    orbitSpeed: 0.005,
  },
  {
    name: "Urano",
    radius: 1.5,
    distance: 55,
    color: 0x00ffff,
    texture: "textures/planets/uranus/main_texture.jpg",
    orbitSpeed: 0.004,
  },
  {
    name: "Neptuno",
    radius: 1.4,
    distance: 65,
    color: 0x0000ff,
    texture: "textures/planets/neptune/main_texture.jpg",
    orbitSpeed: 0.003,
  },
];
